# Site settings
title: Mariita X Aqui
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
